# See https://hbs.razonyang.com/v1/en/docs/widgets/social-links/.
email: contact@tinect.de
#facebook:
github: tinect
gitlab: tinect
linkedin: tinect
#xing: tinect
stackoverflow: 13686440/tinect
twitter: tinect1
#weibo:
#zhihu:
#instagram:
#quora:
#tumblr:
#reddit:
#telegram:
#qq:
#dockerhub:
#bitbucket:
#kaggle:
#medium:
#lastfm:
#bilibili:
#youtube:
#discord:
#discourse:
#facebookgroup:
#tiktok:
#pinterest:
#mastodon:
#liberapay:
paypal: tinect
#patreon:
#tipeee:
