languageCode: "en-us"
baseUrl: "https://blog.tinect.de/"
title: "tinect's blog"
theme: "hugo-theme-bootstrap"

build:
  writeStats: true

menu:
  main:
    - identifier: posts
      name: Posts
      title: Posts
      url: /posts/
      weight: 0
