name: updatetheme

on:
  workflow_dispatch:
  schedule:
    - cron: '30 5 * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: |
          hugo mod get github.com/razonyang/hugo-theme-bootstrap@master
          hugo mod tidy
          hugo mod npm pack
          npm update

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "chore: Update theme"
          title: "Update theme"
          body: ""
          delete-branch: true
          draft: true
          reviewers: tinect
          branch: chore/theme-update
